### ISSUE TITLE
Performance: Small delays when clicking different Discord servers, and in the window appearing when using cmd+tab to switch to Accord

### ISSUE THREAD

**Issue by DannyJJK** [evelyneee/accord#10]
Accord: Version 1.0 (1)
macOS: 12.3 (21E230)
MacBook Pro (13-inch, 2019)

One of the best points of this application is speed, but currently there are some delays when clicking things, and there's also a small delay when using cmd+tab to switch to Accord (more visible when the chat is open on a server, I think it was around 300ms for the window to appear).

I'd love for this application to be really snappy. The readme states performance issues on Big Sur, but I'm on Monterey, so I thought I'd mention this.

Thanks for a native Mac application, I was using Ripcord before, and I was led to this by Ripcord's developer.

**Comment by evelyneee** [comment]
I tried to fix this in the [latest commit](https://github.com/evelyneee/accord/commit/d724a13bec7be16badca3ac22da450c0d175b214

Here is a build you can try with the fix: [Accord.zip](https://github.com/evelyneee/accord/files/8346039/Accord.zip), please let me know if it worked!

**Comment by DannyJJK** [comment]
Clicking on servers feels a bit faster, but it still hangs when doing cmd+tab when a chat is open. Here is a chat with lots of emojis, which I think might be also slowing it down. You can see on the video it takes some time for the window to show in front
https://user-images.githubusercontent.com/11057501/160018993-71bcc678-de78-471a-9483-489f60156abe.mov

**Comment by evelyneee** [comment]
I'll try to profile on a chat with more emojis and see.

**Comment by DannyJJK** [comment]
The example I used was the Noteplan Discord server:
https://discord.gg/D4268MT

Then select the #info room

**Comment by evelyneee** [comment]
I've been working on fixing this, maybe try the latest build. I'll close this atm because it isn't a bug on my side.
