### ISSUE TITLE
Accord doesn't work on macOS Big Sur

### ISSUE THREAD

**Issue by mariobrostech** [evelyneee/accord#15]
Hi,

I know your documentation states that macOS Big Sur support for Accord is questionable at best, but I haven't been able to get it to work at all on my system. After signing in, the client either hangs at the "Connecting" screen or gets to the point of showing my server icons in the sidebar and then completely locks up. In both cases, no messages are visible, thus making the client unusable.

If there's anything I can do to help troubleshoot this, I'd be more than happy to! Just tell me what you'd like in terms of logs, and I'll attach them in a comment.

Thanks in advance 🙂

**Comment by DannyJJK** [comment]
Hey, I'm not the developer but I thought I'd try help out. Sometimes you can see errors on macOS applications if you run them directly from the Terminal. If you open Terminal, if Accord is in your normal Applications folder, you can run it by using this command:
`/Applications/Accord.app/Contents/MacOS/Accord`

Then Accord should open and you should start seeing messages in the Terminal

**Comment by mariobrostech** [comment]
Hi, thanks for being willing to help out! This is a copy of the log that was generated in case it helps the developer diagnose the issue:

```
/Applications/Accord.app/Contents/MacOS/Accord 
[Gateway:44] Preparing 
[Gateway:37] Ready up 
[Extensions] failed to decode keyNotFound(CodingKeys(stringValue: "mention_count", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "d", intValue: nil), CodingKeys(stringValue: "read_state", intValue: nil), CodingKeys(stringValue: "entries", intValue: nil), _JSONKey(stringValue: "Index 419", intValue: 419)], debugDescription: "No value associated with key CodingKeys(stringValue: \"mention_count\", intValue: nil) (\"mention_count\").", underlyingError: nil)) 
[Extensions] failed to decode keyNotFound(CodingKeys(stringValue: "mention_count", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "d", intValue: nil), CodingKeys(stringValue: "read_state", intValue: nil), CodingKeys(stringValue: "entries", intValue: nil), _JSONKey(stringValue: "Index 420", intValue: 420)], debugDescription: "No value associated with key CodingKeys(stringValue: \"mention_count\", intValue: nil) (\"mention_count\").", underlyingError: nil)) 
[Gateway:259] Hello, [Discord username] !! 
[Gateway] Connected with session ID [Redacted in case this is sensitive] 
[ServerListView:27] emotes 
[ServerListView+Misc:123] Binded to guild channels 
[Status:66] ["emoji": ["name": "", "id": "", "animated": false], "name": "Custom Status", "type": 4, "state": <null>] 
[ContentView:98] uh bye 
[ServerListView+Misc:33] Binded to private channels 
[Status:66] ["type": 4, "name": "Custom Status", "state": <null>, "emoji": ["id": "", "animated": false, "name": ""]] 
[ContentView:98] uh bye 
[ContentView:98] uh bye
```

**Comment by evelyneee** [comment]
Hi both of you! Thanks @DannyJJK for the help. I was really busy last week, however I am now on a break from studies so I can focus on this more. I'll most likely get it fixed before Monday; I have a test device for macOS Big Sur

**Comment by mariobrostech** [comment]
Awesome, thank you for working on this!

**Comment by evelyneee** [comment]
Update: I got the test mac today so I'll do it this afternoon

**Comment by mariobrostech** [comment]
This seems to still be an issue in the latest version. However, if you haven't already logged in with a prior version of the app before upgrading, Accord outright crashes at launch on Macs running Big Sur.

**Comment by evelyneee** [comment]
I have been putting this off for a while, I've been really busy. Hopefully I can do it tonight, it'll be in 1.0.1 for sure.

**Comment by evelyneee** [comment]
This is really not easy! I'll have to update the Mac this weekend to the latest Big Sur version because Xcode won't install

**Comment by mariobrostech** [comment]
You actually shouldn't have to do that. If you already have Xcode downloaded on another Mac using your Apple ID, click on your name at the bottom-left corner of the App Store, and download Xcode from your purchased list. Clicking on the download button will prompt you to download the latest version that's compatible with your Mac.

Alternatively, you can download Xcode directly from Apple's developer site. First, [sign into the developer portal](https://developer.apple.com/download/all), and then [click on this link](https://download.developer.apple.com/Developer_Tools/Xcode_13.2.1/Xcode_13.2.1.xip) to install the latest compatible version of Xcode on macOS Big Sur.

Hope that helps!

**Comment by evelyneee** [comment]
I know, but I have to update to at least 11.3 to use Xcode 13

**Comment by mariobrostech** [comment]
Ah, ok, I misread your message and thought you were running the latest version of Big Sur already

**Comment by mariobrostech** [comment]
I'm sure you're already aware of this, but the issue with crashing on macOS Big Sur clients continues in v1.2. I know you're working on this; I'm just letting you know in case you haven't received feedback from anyone else regarding this.

PS: Accord v1.2 has released for Homebrew Cask as of yesterday

Thanks again for your help and willingness to work on this!

**Comment by evelyneee** [comment]
thanks for updating the cask! i'm working on it right now but it's not easy. i'll update the macbook tonight so i can work on it again soon.

**Comment by mariobrostech** [comment]
Awesome, glad to hear you're still working on it! Don't rush it; I just keep commenting on this issue so everyone's aware of whether or not new builds of Accord are fixing this or not. Thanks again for your help 🙂

**Comment by evelyneee** [comment]
macOS Ventura is out and requires a lot of changes. I've left a big sur branch for now but honestly I doubt Big Sur support will ever come now.. 
Supporting those versions would require a lot of tweaking to the codebase. If I ever come back to it, I'll release one update fixing the issues but I can't support Big Sur long term. 
All I can suggest is upgrading to Monterey.

**Comment by evelyneee** [comment]
I'm not gonna completely disregard the idea of bringing it back but as my test devices need to be on Monterey now I can't keep up.

**Comment by percheperche** [comment]
@evelyneee Could you change the minimum OS requirement from Big Sur to Monterey in the README?

**Comment by evelyneee** [comment]
It works on Big Sur though.

**Comment by mariobrostech** [comment]
The last time I checked, Accord wouldn't even run on macOS Big Sur since the Info.plist file got changed to specify the minimum supported OS as macOS Monterey. See my comments here: [https://github.com/Homebrew/homebrew-cask/pull/125781#issuecomment-1157160765](https://github.com/Homebrew/homebrew-cask/pull/125781#issuecomment-1157160765)

**Comment by zandr108** [comment]
Check again

**Comment by evelyneee** [comment]
I added support back recently, it's tested and working

**Comment by mariobrostech** [comment]
Great, thanks for confirming!

**Comment by percheperche** [comment]
Alright, the binaries in the release section do seem to start so it's only a problem of the homebrew incorrectly requiring Monterey. My apologies!
