### ISSUE TITLE
Window disappears after login

### ISSUE THREAD

**Issue by crystall1nedev** [evelyneee/accord#22]
Host: MacBook Pro (13-inch, Mid 2012) running macOS Monterey with OpenCore Legacy Patcher

Issue: Hard to explain, but after I logged into Accord, the window disappeared. Opening new windows shows the loading screen, then those windows disappear as well. They don't show up in Mission Control as invisible, and aren't in the Dock as minimized, they poof out of existence and the only thing showing me they exist is right clicking on the Accord icon in the Dock.

Interestingly, I ran it in the terminal and it worked fine. After alternating between terminal and app icon, it eventually ended up fixing itself. I still don't know enough Swift to figure out why, though.

**Comment by evelyneee** [comment]
This issue will be fixed in an upcoming release that will most likely be available today
