### ISSUE TITLE
Doesn't check if token/login has expired?

### ISSUE THREAD

**Issue by DannyJJK** [evelyneee/accord#31]
OS: macOS Monterey 12.4 (21F79)
Accord: Version 1.3.1 (1)

I generally only open Accord from time to time, I don't use Discord daily. When I used to use Ripcord (another third-party Discord client) it would tell me that my token needs renewing, however when I open Accord after a while of not using it, I just get stuck on "Connecting" until it either times out or I log out. If I log out and then log back in it works fine.

Is there a missing check to see if the current login has expired? It would be nice if it said "Your login has expired, please re-enter your password" maybe with the usual login form but with the last logged in email pre-filled in

**Comment by evelyneee** [comment]
I know about this issue, it was supposed to be working but apparently it's not? I'll work on it today

**Comment by evelyneee** [comment]
fixed in commit d052073
