### ISSUE TITLE
Chat view stays visible.

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [evelyneee/accord#34]
If you click on the input field
<img width="239" alt="image" src="https://user-images.githubusercontent.com/15117158/181381060-247aa289-de34-416d-9892-e6689b8151e2.png">
in a guild channel and switch to another guild the chat view will stay even tho you switched to another guild.

**Comment by evelyneee** [comment]
This is intended behaviour, the channel shouldn't be closed unless something else will replace it.

**Comment by sanderDijkxhoorn** [comment]
> This is intended behaviour, the channel shouldn't be closed unless something else will replace it.

It is very weird to have a channel from another guild open while being in another guild.

**Comment by evelyneee** [comment]
Fixed this a while ago
