### ISSUE TITLE
Pinning a message will show an empty message in the chat.

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [evelyneee/accord#37]
Pinning a message will show an empty message in the chat.

<img width="233" alt="image" src="https://user-images.githubusercontent.com/15117158/181382189-412d24f3-ecb2-45c5-89e6-b182e9a6154e.png">
It is just a blank space.

**Comment by sanderDijkxhoorn** [comment]
Sorry for all the issues, I just want to help in making Accord the best possible so I could use it as my daily driver.

**Comment by evelyneee** [comment]
No worries! I'll take a look at all of these tomorrow, they seem somewhat easy to fix.

**Comment by evelyneee** [comment]
Fixed in 93282102ac919e8006805cc933fa7256fd08a65a
