### ISSUE TITLE
Fails to connect and displays message, "The data couldn't be read because it isn't in the correct format."

### ISSUE THREAD

**Issue by osx86-ijb** [evelyneee/accord#45]
**Upon obtaining via Homebrew installation route, starting the application, logging in with my email/pass/2fa, I am greeted with this:**

<img width="812" alt="Screen Shot 2022-10-06 at 10 52 55 PM" src="https://user-images.githubusercontent.com/67184728/194458244-5ef1bc05-4af4-43bb-804c-f3531434071e.png">

**Comment by y444** [comment]
I have the same issue.

- Downloaded 1.5 release via Releases
- Launched the .app file from Downloads
- Tried moving to Applications with no effect
- Tried removing red.evelyn.accord folders wherever I found them
- Tried downgrading to 1.4.1

**Comment by evelyneee** [comment]
this is fixed in the latest commit. Use the github actions build or wait until I release a new build later today or tomorrow.

**Comment by evelyneee** [comment]
This is fixed in Accord 1.6. Closing the issue
