### ISSUE TITLE
SHA256 mismatch error when trying to install via Homebrew

### ISSUE THREAD

**Issue by JGStyle** [evelyneee/accord#50]
I get the following error when trying to install accord via Homebrew
```
Error: SHA256 mismatch
Expected: 36e8970a058b01c302ffbe2a04ce36a77efb75b7add91e2ff2c10b34073f7d73
  Actual: d469ad5c1a94b7d1d83c504181f386ed8b0151fbf1889229815828d30d2da449
    File: /Users/jgs/Library/Caches/Homebrew/downloads/88cd8c1e579ddd255935615e1fb24398c0b46f755bc06d308879369a78eb774d--Accord.zip
```
I'm running macOS Monterey 12.5 on a MacBook Pro 16" 2021, M1 Pro
Homebrew is installed with the latest version (3.6.6)
I have deleted the file and retried, same results
I have restart the terminal session
I have restarted my computer

**Comment by evelyneee** [comment]
Download it manually from GitHub Actions, the homebrew build won't work
